version: '2'
services:
  web:
    image: bobbysiagian/nginx:stable
    ports:
      - "80:80"
    volumes:
      - /app/web:/app/web
      - /app/logs:/app/log/nginx
      - ./nginx.conf:/etc/nginx/nginx.conf
#the conf.d folder contains nginx server{} settings equal to sites-available
#all files within conf.d must end with *.conf to get autoloaded similar
      - ./conf.d:/etc/nginx/conf.d
      - ./gzip.conf:/etc/nginx/gzip.conf
      - ./php7-fpm.conf:/etc/nginx/php7-fpm.conf
    links:
      - php7
  php7:
    image: bobbysiagian/php:7.1-fpm-extmods-v1
    volumes:
      - /app/web:/app/web
      - ./php.ini:/usr/local/etc/php/php.ini
      - ./www.conf:/usr/local/etc/php-fpm.d/www.conf
